server:
  port: 8081

spring:
  application:
    name: mrp

  datasource:
    url: jdbc:postgresql://localhost:5432/mrp
    username: postgres
    password: e40024041
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true